title: Piotr Trochim
email: ptrochim@pm.me
author: Piotr Trochim
description: >
  Thoughts and results I wish to persist.
baseurl: ""
url: "https://piotrtrochim.net"
github_username: paksas
substack_url: "https://substack.com/@piotrtrochim/posts"

markdown: kramdown
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: false
  input: GFM

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

permalink: /:year/:month/:day/:title/

include:
  - _images

exclude:
  - Gemfile
  - Gemfile.lock
  - build.sh
  - test.sh
  - README.md
  - vendor
