title: Piotr Trochim's blog
email: ptrochim@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Thoughts and results I wish to persist.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://paksas.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: piotrtrochim
github_username:  paksas

# Build settings
markdown: kramdown
kramdown:
  math_engine: mathjax
theme: minima
plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
