title: Piotr Trochim
email: ptrochim@gmail.com
author: Piotr Trochim
description: >
  Thoughts and results I wish to persist.
baseurl: ""
url: "https://piotrtrochim.com"
twitter_username: piotrtrochim
github_username: paksas

markdown: kramdown
kramdown:
  math_engine: mathjax

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

permalink: /:year/:month/:day/:title/

include:
  - _images

exclude:
  - Gemfile
  - Gemfile.lock
  - build.sh
  - test.sh
  - README.md
  - vendor
